import React from 'react';
// import $ from 'jquery';

class StudentsList extends React.Component {
	constructor(props) {
		super();
	}

	componentDidMount() {

	}

	componentWillUnmount() {

	}

	render() {
		return (
			<div className="panel panel-default">
				<div className="panel-heading">
					<i className="fa fa-list fa-fw"></i> لیست دانش آموزان
					<div className="pull-left">
						<div className="btn-group">
							<button><i className="fa fa-refresh"></i></button>
							&nbsp;
							<button><i className="fa fa-close"></i></button>
						</div>
					</div>
				</div>
				<div className="panel-body">
					<div className="row">
						<div className="col-lg-12">
							<div className="table-responsive">
								<table className="table table-bordered table-hover table-striped">
									<thead>
										<tr>
											<th>شماره کلاسی</th>
											<th>نام خانوادگی</th>
											<th>نام پدر</th>
											<th>پایه تحصیلی</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>1</td>
											<td>اصغری</td>
											<td>احمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>2</td>
											<td>صالحی</td>
											<td>مرتضی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>3</td>
											<td>رضایی</td>
											<td>محمد</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>4</td>
											<td>فلاح</td>
											<td>امید</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>5</td>
											<td>اسدی</td>
											<td>عادل</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>6</td>
											<td>غلامی</td>
											<td>عباس</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>7</td>
											<td>محمدی</td>
											<td>علی</td>
											<td>ششم</td>
										</tr>
										<tr>
											<td>8</td>
											<td>زارع</td>
											<td>مجتبی</td>
											<td>ششم</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div className="col-lg-8">
							<div id="morris-bar-chart"></div>
						</div>
					</div>
				</div>
			</div>
		);
	}
}

export default StudentsList;